# Generated by Django 3.2.16 on 2022-11-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.FileField(upload_to='post_images')),
            ],
        ),
    ]
