# Generated by Django 3.2.16 on 2022-11-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_api', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
